# -*- coding: utf-8 -*-
"""cse1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iako1gsazHJvF0DjycJWCaC9mc0ujs-R
"""

!pip install -q kagglehub
!pip install pandas

import kagglehub


path = kagglehub.dataset_download(
    "nalisha/tesla-ea-deliveries-and-production-data20152025"
)

print("Path to dataset files:", path)

import os

path = "/kaggle/input/tesla-ea-deliveries-and-production-data20152025"
print(os.listdir(path))

"""if path eror past the above path"""

import pandas as pd
# inside paste path you above  got with / name of your csv file
df = pd.read_csv(   "/kaggle/input/tesla-ea-deliveries-and-production-data20152025/tesla_deliveries_dataset_2015_2025.csv"
)

import pandas as pd
import numpy as np

from sklearn.model_selection import TimeSeriesSplit
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import (
    OneHotEncoder,
    StandardScaler
)

from sklearn.impute import SimpleImputer

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

from xgboost import XGBRegressor

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

df.shape
df.head()

df.isnull().values.any()

import matplotlib.pyplot as plt


df.hist(figsize=(12,9))
plt.show()

df.describe()

#for sales
df["Estimated_Deliveries"].describe()

#for proce
df["Avg_Price_USD"].describe()

sns.histplot(df["Estimated_Deliveries"])

numeric_cols = df.select_dtypes(
    include=np.number
).columns

corr = df[numeric_cols].corr()

plt.figure(figsize=(12,8))

sns.heatmap(
    corr,
    annot=True
)

corr["Estimated_Deliveries"]\
.sort_values(ascending=False)

df["Estimated_Deliveries"].describe()

df["Estimated_Deliveries"].describe()

df["Avg_Price_USD"].describe()

df.groupby("Model")[
    "Avg_Price_USD"
].mean().sort_values()

df.groupby("Model")[
    "Estimated_Deliveries"
].mean().sort_values()

corr["Avg_Price_USD"].sort_values(ascending=False)

df[[
"Avg_Price_USD",
"Battery_Capacity_kWh",
"Range_km"
]].corr()

df.groupby("Region")["Avg_Price_USD"].mean()

df.groupby("Source_Type")["Avg_Price_USD"].mean()

df.groupby(["Region","Model"])["Avg_Price_USD"].mean()

num_cols = [
    "Year",
    "Month",
    "Production_Units",
    "Avg_Price_USD",
    "Battery_Capacity_kWh",
    "Range_km",
    "CO2_Saved_tons",
    "Charging_Stations"
]

cat_cols = [
    "Region",
    "Model",
    "Source_Type"
]

num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

sales_pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("model", LinearRegression())
])

X = df.drop(columns=["Estimated_Deliveries"])

y = df["Estimated_Deliveries"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

sales_pipeline.fit(X_train, y_train)

predictions = sales_pipeline.predict(X_test)

mae = mean_absolute_error(y_test, predictions)

rmse = np.sqrt(
    mean_squared_error(y_test, predictions)
)

r2 = r2_score(y_test, predictions)

print("MAE :", mae)
print("RMSE:", rmse)
print("R2  :", r2)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

plt.scatter(
    y_test,
    predictions,
    alpha=0.6
)

plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    'r--'
)

plt.xlabel("Actual Deliveries")
plt.ylabel("Predicted Deliveries")
plt.title("Actual vs Predicted Deliveries")

plt.show()



"""now for estimated price"""

num_cols = [

    "Year",
    "Month",

    "Estimated_Deliveries",

    "Production_Units",

    "Battery_Capacity_kWh",

    #"Range_km",

    "CO2_Saved_tons",

    "Charging_Stations"

]

cat_cols = [
    "Region",
    "Model",
    "Source_Type"
]

num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([

    (
        "imputer",
        SimpleImputer(strategy="most_frequent")
    ),

    (
        "encoder",
        OneHotEncoder(handle_unknown="ignore")
    )

])

preprocessor = ColumnTransformer([

    (
        "num",
        num_pipeline,
        num_cols
    ),

    (
        "cat",
        cat_pipeline,
        cat_cols
    )

])

price_pipeline = Pipeline([

    (
        "preprocessing",
        preprocessor
    ),

    (
        "model",
        LinearRegression()
    )

])

X = df.drop(columns=["Avg_Price_USD"])

y = df["Avg_Price_USD"]

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.20,

    random_state=42

)

price_pipeline.fit(
    X_train,
    y_train
)

price_preds = price_pipeline.predict(
    X_test
)

mae = mean_absolute_error(y_test, predictions)

rmse = np.sqrt(
    mean_squared_error(y_test, predictions)
)

r2 = r2_score(y_test, predictions)

print("MAE :", mae)
print("RMSE:", rmse)
print("R2  :", r2)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

plt.scatter(
    y_test,
    predictions,
    alpha=0.6
)

plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    'r--'
)

plt.xlabel("Actual estimated")
plt.ylabel("Predicted estimated")
plt.title("Actual vs Predicted price")

plt.show()

